import { describe, expect, it } from 'vitest';
import { evaluatePosition } from '../src/evaluate-position.js';
import { wasmEngine } from './helpers/wasm-engine.js';

/**
 * Tier 2: a real engine, invariants only — never a specific number.
 *
 * This is the suite that would have caught the prototype's bug. Its 28 mocked test files
 * could not, because the fixture encoded the same misunderstanding as the code: a number
 * was fed in and then asserted to be White-relative. Here the numbers come from
 * Stockfish, and the assertions are contracts about their *sign* and *provenance*.
 *
 * Runs on every push against the WASM build — no Docker.
 */

/**
 * White is down a queen for a pawn and it is **Black** to move, so Stockfish reports a
 * *positive* Raw Score. The prototype shipped that as "White is winning".
 *
 * Reached by `1.e4 e5 2.Qh5 Nc6 3.Qxf7+ Kxf7 4.Nf3` — White 30 points of material to
 * Black's 38. Every FEN in this file was generated by replaying its moves and checking
 * the material and mate status, rather than written out by hand.
 */
const WHITE_DOWN_A_QUEEN_BLACK_TO_MOVE =
  'r1bq1bnr/pppp1kpp/2n5/4p3/4P3/5N2/PPPP1PPP/RNB1KB1R b KQ - 1 4';

/** The mirror as a control: Black down a queen, White to move. `1.e4 e5 2.Nf3 Qh4 3.Nxh4 Nc6`. */
const BLACK_DOWN_A_QUEEN_WHITE_TO_MOVE =
  'r1b1kbnr/pppp1ppp/2n5/4p3/4P2N/8/PPPP1PPP/RNBQKB1R w KQkq - 1 4';

/** White to move plays Qh5#. Reached by `1.e4 f5 2.d3 g5`. */
const WHITE_MATES_IN_1 = 'rnbqkbnr/ppppp2p/8/5pp1/4P3/3P4/PPP2PPP/RNBQKBNR w KQkq - 0 3';

/** Fool's mate: Black to move plays Qh4#. Reached by `1.f3 e5 2.g4`. */
const BLACK_MATES_IN_1 = 'rnbqkbnr/pppp1ppp/8/4p3/6P1/5P2/PPPPP2P/RNBQKBNR b KQkq - 0 2';

const BUDGET_MS = 1_000;

describe('the sign survives a real search', () => {
  it('reports a Black-to-move winning position as negative for White', async () => {
    const result = await evaluatePosition(wasmEngine(), {
      fen: WHITE_DOWN_A_QUEEN_BLACK_TO_MOVE,
      movetimeMs: BUDGET_MS,
    });

    // The whole point of the server, in one assertion.
    expect(result.evaluation?.evaluation_cp).toBeLessThan(0);
  });

  it('ships the positive Raw Score beside it, so the conversion is auditable', async () => {
    const result = await evaluatePosition(wasmEngine(), {
      fen: WHITE_DOWN_A_QUEEN_BLACK_TO_MOVE,
      movetimeMs: BUDGET_MS,
    });

    // The engine really did say "good for me" — the sign flip is the server's work, and a
    // reader can see both halves rather than trusting one.
    expect(result.evaluation?.raw_score_cp).toBeGreaterThan(0);
    expect(result.evaluation?.side_to_move).toBe('b');
  });

  it('reports the mirrored position as positive for White', async () => {
    const result = await evaluatePosition(wasmEngine(), {
      fen: BLACK_DOWN_A_QUEEN_WHITE_TO_MOVE,
      movetimeMs: BUDGET_MS,
    });

    expect(result.evaluation?.evaluation_cp).toBeGreaterThan(0);
  });

  it('gives White-relative WDL that is loss-heavy when White is losing', async () => {
    const result = await evaluatePosition(wasmEngine(), {
      fen: WHITE_DOWN_A_QUEEN_BLACK_TO_MOVE,
      movetimeMs: BUDGET_MS,
    });

    const wdl = result.evaluation?.wdl_white;
    expect(wdl).toBeDefined();

    // Negating centipawns is not enough: WDL needs win and loss *swapped*. If it were
    // merely passed through, this triple would be win-heavy — the engine reported it from
    // Black's side, and Black is winning.
    const [win, , loss] = wdl ?? [0, 0, 0];
    expect(loss).toBeGreaterThan(win);
  });

  it('ships the raw triple win-heavy beside it, so the swap is auditable', async () => {
    const result = await evaluatePosition(wasmEngine(), {
      fen: WHITE_DOWN_A_QUEEN_BLACK_TO_MOVE,
      movetimeMs: BUDGET_MS,
    });

    // The engine's own view: Black is to move and winning, so *its* win figure is high.
    // Both halves ship, so a reader checks the conversion instead of trusting it.
    const [rawWin, , rawLoss] = result.evaluation?.raw_wdl ?? [0, 0, 0];
    expect(rawWin).toBeGreaterThan(rawLoss);
  });

  it('gives a White-relative WDL that differs from the raw one when Black is to move', async () => {
    const result = await evaluatePosition(wasmEngine(), {
      fen: WHITE_DOWN_A_QUEEN_BLACK_TO_MOVE,
      movetimeMs: BUDGET_MS,
    });

    // An identity conversion cannot pass this: on a decisive position the two forms are
    // mirror images, so equality here means the swap never happened.
    expect(result.evaluation?.wdl_white).not.toEqual(result.evaluation?.raw_wdl);
  });

  it('leaves the two forms equal when White is to move', async () => {
    const result = await evaluatePosition(wasmEngine(), {
      fen: BLACK_DOWN_A_QUEEN_WHITE_TO_MOVE,
      movetimeMs: BUDGET_MS,
    });

    // Nothing to mirror — the engine already spoke from White's side.
    expect(result.evaluation?.wdl_white).toEqual(result.evaluation?.raw_wdl);
  });

  it('gives a win-heavy White-relative WDL when White is winning', async () => {
    const result = await evaluatePosition(wasmEngine(), {
      fen: BLACK_DOWN_A_QUEEN_WHITE_TO_MOVE,
      movetimeMs: BUDGET_MS,
    });

    const [win, , loss] = result.evaluation?.wdl_white ?? [0, 0, 0];
    expect(win).toBeGreaterThan(loss);
  });
});

describe('a forced mate is a distance, not centipawns', () => {
  it('reports White mating in 1 as a positive mate distance', async () => {
    const result = await evaluatePosition(wasmEngine(), {
      fen: WHITE_MATES_IN_1,
      movetimeMs: BUDGET_MS,
    });

    expect(result.evaluation?.mate_in).toBe(1);
    // Never faked as a large centipawn score — the two are different quantities.
    expect(result.evaluation?.evaluation_cp).toBeNull();
  });

  it('reports Black mating in 1 as a negative mate distance', async () => {
    const result = await evaluatePosition(wasmEngine(), {
      fen: BLACK_MATES_IN_1,
      movetimeMs: BUDGET_MS,
    });

    expect(result.evaluation?.mate_in).toBe(-1);
    expect(result.evaluation?.evaluation_cp).toBeNull();
  });
});

describe('every result carries its provenance', () => {
  it('names the engine, its version, and its build', async () => {
    const result = await evaluatePosition(wasmEngine(), {
      fen: WHITE_DOWN_A_QUEEN_BLACK_TO_MOVE,
      movetimeMs: BUDGET_MS,
    });

    expect(result.evidence.engine).toContain('Stockfish');
    expect(result.evidence.engine_version).not.toBeNull();
    expect(result.evidence.build).toBe('wasm');
  });

  it('reports a depth the search actually reached, with the nodes to back it', async () => {
    const result = await evaluatePosition(wasmEngine(), {
      fen: WHITE_DOWN_A_QUEEN_BLACK_TO_MOVE,
      movetimeMs: BUDGET_MS,
    });

    // Asserted as an outcome, not a number: nothing requested a depth, so any positive
    // depth here was reached by searching.
    expect(result.evidence.depth_reached).toBeGreaterThan(0);
    expect(result.evidence.nodes).toBeGreaterThan(0);
    expect(result.evidence.time_ms).toBeGreaterThan(0);
  });

  it('carries the resolved FEN and a principal variation, so the search can be re-run', async () => {
    const result = await evaluatePosition(wasmEngine(), {
      fen: WHITE_DOWN_A_QUEEN_BLACK_TO_MOVE,
      movetimeMs: BUDGET_MS,
    });

    expect(result.evidence.resolved_fen).toBe(WHITE_DOWN_A_QUEEN_BLACK_TO_MOVE);
    expect(result.best?.pv_uci.length).toBeGreaterThan(0);
    expect(result.best?.san).not.toBe('');
  });

  it('reports the depth reached under a short budget rather than throwing', async () => {
    // Exhausting the budget is a normal result carrying the deepest completed iteration.
    const result = await evaluatePosition(wasmEngine(), {
      fen: WHITE_DOWN_A_QUEEN_BLACK_TO_MOVE,
      movetimeMs: 50,
    });

    expect(result.evidence.depth_reached).toBeGreaterThan(0);
    expect(result.best).not.toBeNull();
  });
});

/**
 * Tier 2: a Candidate Move scored by a real search.
 *
 * The losing-move case is the one the tool exists for, and the one a "look for it among
 * the top N lines" implementation silently fails: a blunder is not in the top N, so that
 * method returns nothing precisely when the answer is *yes, badly*.
 */
describe('a Candidate Move gets a number even when it is terrible', () => {
  it('scores a queen blunder that appears in no top engine line', async () => {
    // 1.e4 e5 2.Nf3 Nc6 3.Bc4 — White to move has a sound position. `Qh5` is not the
    // blunder here; hanging the queen with Bxf7+ then Qh5 would be. Use a position where
    // a specific move drops material outright.
    const result = await evaluatePosition(wasmEngine(), {
      fen: 'r1bqkbnr/pppp1ppp/2n5/4p3/2B1P3/5N2/PPPP1PPP/RNBQK2R w KQkq - 4 4',
      candidate: 'Bxf7+',
      movetimeMs: BUDGET_MS,
    });

    // The move is legal, so it gets an exact number rather than a null.
    expect(result.candidate).not.toBeNull();
    expect(result.candidate?.san).toBe('Bxf7+');

    // It is worse than the engine's own choice, White-relative.
    expect(result.candidate?.delta_cp).toBeLessThan(0);
  });

  it('scores a candidate the engine never lists, at its own depth', async () => {
    const result = await evaluatePosition(wasmEngine(), {
      fen: 'r1bqkbnr/pppp1ppp/2n5/4p3/2B1P3/5N2/PPPP1PPP/RNBQK2R w KQkq - 4 4',
      candidate: 'Rg1',
      movetimeMs: BUDGET_MS,
    });

    expect(result.candidate?.evaluation.evaluation_cp).not.toBeNull();
    expect(result.candidate?.depth_reached).toBeGreaterThan(0);
  });

  it('keeps the Candidate White-relative: a move good for Black reads negative', async () => {
    // Black to move, and Black is winning. A sound Black move keeps the number
    // *negative*, on the same convention as the main Evaluation.
    const result = await evaluatePosition(wasmEngine(), {
      fen: WHITE_DOWN_A_QUEEN_BLACK_TO_MOVE,
      candidate: 'Qf6',
      movetimeMs: BUDGET_MS,
    });

    expect(result.candidate?.evaluation.evaluation_cp).toBeLessThan(0);
  });
});

/**
 * Tier 2: a Move Sequence resolves to a real board and is searched there.
 *
 * The invariant, not a number: the same position reached two ways — pasted as a FEN, or
 * played out as moves — must be scored the same way.
 */
describe('a Move Sequence lands on the board it names', () => {
  it('evaluates the final position of a sequence, matching the equivalent FEN', async () => {
    const fromMoves = await evaluatePosition(wasmEngine(), {
      moves: '1. e4 e5 2. Qh5 Nc6 3. Qxf7+ Kxf7 4. Nf3',
      movetimeMs: BUDGET_MS,
    });

    // The sequence reaches exactly the board the other tests paste in by hand.
    expect(fromMoves.position.resolved_fen).toBe(WHITE_DOWN_A_QUEEN_BLACK_TO_MOVE);
    // And it is scored on the same convention: White is down a queen.
    expect(fromMoves.evaluation?.evaluation_cp).toBeLessThan(0);
  });

  it('echoes the Start Position beside the resolved one, so the search is locatable', async () => {
    const result = await evaluatePosition(wasmEngine(), {
      moves: '1. e4 e5 2. Nf3',
      movetimeMs: BUDGET_MS,
    });

    expect(result.position.start_fen).toBe(
      'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1',
    );
    expect(result.position.resolved_fen).not.toBe(result.position.start_fen);
    expect(result.position.ply).toBe(3);
  });
});
